let a=15;
let b=5;
let sum = a+b;
let difference = a-b;
let product = a*b;
let quotient = a/b;
console.log("sum",sum);
console.log("difference",difference);
console.log("product",product);
console.log("quotient",quotient);